// 비공개 포트폴리오 사례 데이터. 문장은 옵시디언 원본과 같고, 노드·등급·id는 이 파일이 단일 출처다.
// tier: featured = 대표 카드(문제→판단→결과 흐름), brief = 한 줄, list = 목록, drop = 표시하지 않음

export type Layer = 'product' | 'user' | 'team' | 'misc';
export type Tier = 'featured' | 'brief' | 'list' | 'drop';
// 당근 JD가 보고 싶어 하는 세 갈래
export type Kind = 'user-problem' | 'team-efficiency' | 'tech-review';

export type PfCaseData = {
  id: string;
  layer: Layer;
  node: string;
  tier: Tier;
  title: string;
  when?: string;
  note?: string;
  summary?: string;
  problem?: string;
  cause?: string;
  solution?: string;
  decision?: string;
  result?: string;
  lesson?: string;
  metric?: string;
  metricLabel?: string;
  items?: string[];
  contribution?: string;
  kinds?: Kind[];
};

export const CASES: PfCaseData[] = [
  { id: "gene-2-feedback", layer: "product", node: "user-first", tier: "featured", title: "유전자검사", when: "2026", note: "2.0 리뉴얼", summary: "FF로 열린 2.0을 끝까지 써 보고 피드백 3범주로 정리, 1.0 잔재 26,485줄 순감소", problem: "FF로 열린 2.0을 정식 UX 리서치 전에 검증할 사람이 없었고, 1.0을 만든 팀원들만 아는 리스크가 흩어져 있었음", solution: "유저로서 끝까지 써 보고 UX·폐기·정책 3범주로 피드백을 정리해 PM에게 전달. 팀원들이 아는 리스크도 같은 형식으로 모음", decision: "PM이 판단할 수 있는 형식으로 모아 주는 것이 개발자의 몫이라고 보고, 의견이 아니라 범주와 근거로 전달", result: "롤아웃 확정 후 1.0 잔재를 7단계 스택 PR로 하루에 정리, 638개 파일에서 26,485줄 순감소", metric: "26,485줄", metricLabel: "1.0 잔재 순감소", contribution: "웹 테크스펙 리드·핸즈온. 피드백 정리와 7단계 클린업 PR은 단독", kinds: ["user-problem"] },
  { id: "premium-policy-4", layer: "product", node: "code-to-plan", tier: "featured", title: "보험 · 보험료 줄이기", when: "2026", note: "내보험탭 모듈", summary: "기획서에 빠진 정책 4건을 코드에서 역으로 읽어 개발 전에 확정, 마일스톤 6일 앞서 제출", problem: "기존 코드에는 있지만 기획서에 빠진 정책 4건(재연결 판정·보험가이드·샘플데이터·할인제도)", cause: "PM이 기존 개발 내용을 모르거나 잊어 기획서에 옮기지 못함", solution: "테크스펙 단계에서 코드를 역으로 읽어 PM에게 되돌려 확정", decision: "개발 중에 발견하면 재작업 비용이 크므로 개발 전에 닫는 것을 우선", result: "개발분 전량을 마일스톤 6일 앞서 제출", metric: "6일", metricLabel: "마일스톤 앞서 제출", contribution: "웹 개발 전량 담당. 코드 역추적과 PM 확정 요청 단독", kinds: ["team-efficiency"] },
  { id: "money-format", layer: "product", node: "code-to-plan", tier: "featured", title: "보험 · 금액 표기 규칙", when: "2026", summary: "흩어진 금액 표기 로직을 프리셋 4종으로 통합하고 스토리북을 열어 PM이 코드 규칙에 기획을 맞추게 함", problem: "PM마다 다르게 기획한 금액 표기(반올림·기준액·노출 단위)가 코드에 흩어져 중복 로직 파일 3개", solution: "프리셋 4종으로 통합하고, 스토리북 비교 테이블을 열어 PM이 코드 규칙을 보고 기획을 맞추도록 역제안. 경계값 테스트 36건", decision: "규칙의 단일 진실 원천을 코드에 두고 기획이 거기에 맞추는 편이 재발을 막는다고 판단", result: "이후 5,000원 미만이 0원으로 보이던 버그는 반올림 결과가 0이면 원본을 반환하도록 고치고, 총액 불일치 허용을 문서화", lesson: "규칙의 단일 진실 원천은 코드에 두고 기획이 거기에 맞추게 해야 재발하지 않는다", metric: "36건", metricLabel: "경계값 테스트", contribution: "프리셋 통합·스토리북·경계값 테스트 단독", kinds: ["team-efficiency", "tech-review"] },
  { id: "coverage-exp-restart", layer: "product", node: "rollout", tier: "brief", title: "보험 · 보장분석", when: "2026", note: "보장기간 섹션 실험", summary: "겹친 실험을 종료·클린업한 뒤 새 실험으로 가자고 제안해 PM과 합의", problem: "실험 설계가 겹쳐 돌아가 복잡도가 높아지고, 기존 실험은 p-value가 나오지 않을 상황", solution: "기존 실험을 종료하고 클린업한 뒤 새 실험으로 가자고 제안", decision: "결과가 나오지 않을 실험을 유지하는 비용보다 정리하고 다시 시작하는 비용이 작다고 판단", result: "PM과 합의" },
  { id: "happytalk-integration", layer: "product", node: "revenue-path", tier: "brief", title: "해피톡 연동", summary: "상담신청부터 카카오톡 채팅 오픈까지의 프론트엔드 연동을 최초 구성", solution: "상담신청부터 해피톡 카카오톡 채팅 오픈까지의 프론트엔드 연동을 최초 구성. GA 할당과 약관은 서버와 함께 설계하고, 토큰 3종으로 상담 레코드와 채팅방을 매핑" },
  { id: "consult-loss-constraint", layer: "product", node: "revenue-path", tier: "featured", title: "상담 유실을 막는 제약 규명", summary: "채팅 오픈 API 구조를 분석해 파라미터가 통째로 무시되는 조건을 밝혀 문서화", problem: "상담 레코드와 채팅방을 잇는 커스텀 파라미터가 조건에 따라 통째로 무시되면 상담이 유실됨", cause: "채팅 오픈 API가 HTML을 내려 안에서 JS가 실행되는 구조. 챗봇 자동발화 이벤트가 걸리면 파라미터가 전부 무시되고, 20자 제한과 구분자 문자에 유실됨", solution: "구조를 분석해 제약을 밝히고 문서화", contribution: "API 구조 분석과 제약 문서화 단독", kinds: ["user-problem"] },
  { id: "consult-recovery", layer: "product", node: "revenue-path", tier: "featured", title: "실패한 상담을 되찾는 절차", summary: "전환 오류 장애 뒤 감지·원인 분류·처리 절차를 가이드라인으로 만들고 채널 UID를 양쪽에 저장", problem: "전환 오류 장애로 상담이 유실됨", solution: "감지 → 원인 분류(뱅샐 웹·해피톡 서버·스펙) → 처리 절차를 가이드라인으로 정리하고, 전환 실패 유저를 추적할 수 있게 채널 UID를 양쪽에 저장", decision: "외부사 커뮤니케이션은 고객사인 GA에 위임한다는 원칙 수립", result: "같은 일이 다시 나도 상담을 잃지 않는 절차 확보", contribution: "절차 설계 주도, 채널 UID 저장은 서버와 협업", kinds: ["user-problem", "team-efficiency"] },
  { id: "family-history", layer: "product", node: "revenue-path", tier: "brief", title: "가족력 완벽대비", when: "2026", summary: "가족력 맥락을 떼어 낸 신규 보험 제품을 스캐폴딩부터 상담 연결까지 단독 구현", solution: "보험료 줄이기·보장분석처럼 보험 제품 하나로 가족력 맥락을 떼어 낸 신규 제품을 스캐폴딩부터 입력·동의·결과 화면, 보험상담 연결까지 단독 구현", result: "상담 진입 경로를 하나 더 만듦" },
  { id: "gene-b2c-timer", layer: "product", node: "revenue-path", tier: "featured", title: "B2C 런칭", when: "2021", summary: "유전자검사를 처음부터 B2C로 열며 웹 메인 개발, 선착순 카운트다운 타이머를 절대 시각 기준으로 재설계", problem: "선착순 운영에서 VoC가 가장 예민했던 카운트다운 타이머. 같은 시각에 들어온 유저들의 남은 시간이 서로 다르게 보인다는 문의", cause: "1초씩 빼는 setInterval은 기기와 탭 상태에 따라 지연이 누적됨", solution: "서버가 준 남은 시간을 절대값으로 두고 requestAnimationFrame timestamp로 경과 시간을 계산하는 타이머로 교체", result: "기기와 탭 상태에 관계없이 같은 시각에 같은 숫자가 보임. 그 외 반송·타임라인·결과 페이지 개발", lesson: "시간은 클라이언트가 세지 말고 서버가 준 절대값에서 계산한다", contribution: "웹 메인 개발. 타이머 재설계 단독", kinds: ["user-problem", "tech-review"] },
  { id: "revenue-owner", layer: "product", node: "measure", tier: "brief", title: "매출 여정을 지키는 책임 주체 신설", when: "2026", summary: "라우팅 영역 책임 그룹을 신설하고 책임 범위와 운영 단계를 스펙으로 정의", problem: "매출에 직결되는 여정을 지키는 주체가 정해져 있지 않았음", solution: "“매출 직결 여정 보호, 유입 컨텍스트를 전환까지 운반”을 원칙으로 라우팅 영역 책임 그룹을 신설하고, 책임 범위와 운영 단계를 스펙으로 정의", decision: "누가 지키는지를 먼저 정해야 측정과 대응이 이어진다고 판단" },
  { id: "experiment-observability", layer: "product", node: "measure", tier: "featured", title: "실험 관측 인프라: 보이지 않던 실패를 보이게", when: "2026", summary: "기록되지 않던 실험 배정 실패를 Sentry로 계측하고 오탐 11만 건을 원인별로 분리, 시간당 420~500건에서 10~20건으로", problem: "treatment 100% 롤아웃에도 대조군 유입이 이어지는데 기록이 없었음", cause: "SDK가 예외를 던지지 않아 실패가 조용히 지나감. 14일간 110,455건(66,595명)의 오탐이 원인 구분 없이 섞여 있었음", solution: "“빈 variant”를 신호로 Sentry 계측하고 fetch 실패와 타겟팅 제외를 태그로 구분. 오탐을 원인별로 error·warning·미보고로 분리하고 fetch 전용 prefetch API를 노출해 오용 경로 제거", decision: "실험군 태그를 조회 경로가 수렴하는 한 곳에 세팅해 호출부 수정 없이 전 조직에 적용되게 함", result: "배포 직후 시간당 420~500건에서 10~20건으로, 신규 릴리즈에서는 0건", lesson: "SDK가 조용히 실패하면 \"값이 없다\"는 것 자체를 신호로 계측해야 한다", metric: "420~500 → 10~20", metricLabel: "시간당 오탐, 신규 릴리즈 0건", contribution: "계측 설계·구현 단독, 전 조직 적용", kinds: ["team-efficiency", "tech-review"] },
  { id: "oncall-checklist", layer: "product", node: "oncall", tier: "featured", title: "온콜 아침 체크리스트와 리포트 4종", when: "2023 ~ 2026", summary: "매일 9시 슬랙 워크플로가 4단계 체크리스트와 자동 리포트를 보내 사람은 확인과 대응만 하게 함", problem: "2주 로테이션 데일리 온콜이 사람의 기억에 의존함", solution: "매일 9시 슬랙 워크플로가 배포 후보군 업로드, Sentry 이슈 확인, 404 확인, Amplitude 이상 지표 확인 4단계를 보내고 완료 이모지로 닫음. 각 단계에 배포 티켓 자동 추출, Sentry 전일 대조, 404 집계 스킬, Amplitude 이상 징후 리포트가 자동으로 붙음", decision: "2026년 보안 검토에서 API 키 방식이 불허되자 Custom Agent로 경로를 바꿔 매일 10시에 리포트가 도착하게 함", result: "사람은 확인과 대응만 함. 보험 매출 퍼널 Amplitude 대시보드는 2023년에 혼자 만들었고 매출 중요도가 높은 퍼널 대부분을 포함", contribution: "슬랙 워크플로와 리포트 자동화 본인 제작, 퍼널 대시보드는 2023년에 혼자", kinds: ["team-efficiency"] },
  { id: "ios-android-open", layer: "user", node: "native", tier: "brief", title: "iOS·Android 오픈 방식 차이", when: "2023", summary: "iOS 딥링크와 Android openView의 인코딩 이중 적용 버그를 고치고 실험키로 통일", problem: "보장분석에서 연결관리로 넘어가는 퍼널에서 인코딩이 이중 적용되는 버그", cause: "iOS는 딥링크, Android는 openView로 열어 오픈 방식이 달랐음", solution: "openView는 미인코딩으로 고치고, 실험키로 iOS도 통일" },
  { id: "webview-history", layer: "user", node: "native", tier: "featured", title: "웹뷰 히스토리와 네이티브 닫힘", when: "2026", summary: "replace 체인으로 히스토리 depth가 0이라 뒤로가기에 웹뷰가 닫히던 문제를 push·back 조합으로 해결", problem: "수정 페이지에서 뒤로가기하면 웹뷰가 닫힘", cause: "전 구간이 replace 체인이라 히스토리 depth가 0이고, depth 0의 뒤로가기는 네이티브가 웹뷰를 닫는 동작", solution: "결과→수정은 push, 제출 후 back으로 변경", decision: "replace로 결과를 다시 쌓는 방법은 “결과에서 뒤로가기 한 번에 닫힘” 정책이 깨져 기각", lesson: "해결책이 기존 정책을 깨는지 먼저 확인하고, 깨면 기각한다", contribution: "원인 분석·수정 단독", kinds: ["user-problem"] },
  { id: "webview-mutation-hang", layer: "user", node: "data", tier: "featured", title: "플랫폼별 문제 상황 파악", when: "2026", summary: "요청도 에러도 없이 무한 로딩되던 웹뷰 mutation을 두 원인으로 좁혀 해결", problem: "웹뷰 mutation이 요청도 에러도 없이 무한 로딩", cause: "react-query 특정 버전의 networkMode 오류, iOS 시뮬레이터가 onLine을 잘못 내려줌", solution: "재현으로 두 원인을 좁혀 해결", contribution: "재현·원인 분리·수정 단독", kinds: ["user-problem", "tech-review"] },
  { id: "write-once-cache", layer: "user", node: "data", tier: "brief", title: "데이터 정합성", summary: "write-once 데이터 성격을 근거로 staleTime: Infinity + cancelQueries로 race 해결", problem: "캐시 갱신 순서가 어긋나 옛 값이 화면에 남는 race", solution: "staleTime: Infinity와 cancelQueries의 이중 안전장치", decision: "한 번 쓰면 바뀌지 않는 write-once 데이터 성격을 근거로 재조회 자체를 막는 쪽을 택함", kinds: ["tech-review"] },
  { id: "cache-strategy", layer: "user", node: "data", tier: "brief", title: "캐시 전략", summary: "화면 구조에 따라 removeQueries 교체와 setQueryData 즉시 동기화를 나눠 적용", solution: "useState 스냅샷 구조인 화면은 invalidate 대신 removeQueries로 교체. 다른 화면은 setQueryData 즉시 동기화", decision: "후자는 refetch 완료 전 재진입 race가 있어 invalidate로는 막을 수 없다고 판단", kinds: ["tech-review"] },
  { id: "react-children", layer: "user", node: "render", tier: "brief", title: "React children", when: "2026", summary: "Children.toArray가 Fragment를 풀지 않는 점을 재귀 평탄화로 해결", cause: "Children.toArray가 Fragment를 풀지 않음", solution: "재귀 평탄화로 해결, 재현 테스트 추가" },
  { id: "css-line-box", layer: "user", node: "render", tier: "brief", title: "CSS line box", when: "2026", summary: "공백 노드가 line box를 만들지 않아 어긋난 baseline을 nbsp로 해결, 공용 컴포넌트라 4곳 동시 해소", cause: "공백 노드가 line box를 만들지 않아 baseline이 어긋남", solution: "nbsp로 해결", result: "공용 컴포넌트라 4곳 동시 해소" },
  { id: "health-indexing", layer: "user", node: "organic", tier: "featured", title: "health 전체 인덱싱 정리", when: "2025.12", summary: "sitemap 부재와 과정 페이지 노출을 혼자 먼저 정리해 검색 결과를 의도한 페이지 위주로 정상화", problem: "sitemap이 없어 의도한 페이지는 색인되지 않고, 본인인증·상담신청 과정 페이지는 오히려 검색에 노출. 오가닉 유저 UX와 브랜딩 리스크", solution: "노출할 페이지는 sitemap 추가와 콘솔 재제출, 막을 페이지는 robots 처리와 색인 제거", decision: "검색 스코어링이 시간에 따라 쌓이는 구조라 다른 부채보다 우선순위를 올려 혼자 먼저 정리", result: "검색 결과를 의도한 페이지 위주로 정상화하고, 문제·조치·임팩트를 PM에게 서면으로 공유", lesson: "시간이 지날수록 쌓이는 자산은 다른 부채보다 먼저 손댄다", contribution: "혼자 먼저 정리하고 PM에게 서면 공유", kinds: ["user-problem", "team-efficiency"] },
  { id: "premium-web-sitemap", layer: "user", node: "organic", tier: "brief", title: "보험 · 보험료 줄이기 web", when: "2025", summary: "SEO 메타 스펙에 색인 요청이 빠진 점을 짚어 sitemap 등록을 함께 진행, PM SEO 강의로 이어짐", problem: "앱 전용 솔루션에 웹 버전을 만들며 PM이 잡은 SEO 메타 스펙에 색인 요청이 없어 검색봇이 못 들어옴", solution: "“검색 노출이 목적이면 메타만으로는 안 된다”고 짚어 sitemap 등록을 같이 진행. PL 요청으로 보험진단 전체 인덱싱 점검", decision: "스펙마다 색인이 챙겨지려면 개별 수정이 아니라 보험 PM 가이드가 필요하다고 제기", result: "이듬해 PM SEO 강의로 이어짐" },
  { id: "naver-indexnow", layer: "user", node: "organic", tier: "featured", title: "네이버 미색인 진단과 색인 자동화", when: "2026", summary: "색인·노출·트래킹 세 단계 진단으로 원인을 SERP 개편으로 좁히고, IndexNow 연동으로 색인 요청 자동화", problem: "네이버 검색 로직 변경 뒤 콘텐츠 유입이 급감했다는 마케터 문의", cause: "색인·노출·트래킹 세 단계로 진단해 트래킹은 정상임을 걸러 내고 SERP 개편으로 좁힘", solution: "손댈 수 있는 SEO 경고 개선과 dateModified JSON-LD 배포. 템플릿 변경으로 전 페이지 재색인이 필요해지자 벌크 요청 스크립트와 IndexNow 연동", result: "신규·수정 페이지 색인 요청 자동화", contribution: "진단 틀·조치·자동화 단독", kinds: ["user-problem"] },
  { id: "qr-bridge", layer: "user", node: "offline", tier: "featured", title: "유전자 키트 QR 브릿지 페이지", when: "2023", summary: "키트에 인쇄된 QR이 URL 변경에 취약해 팀이 제어하는 브릿지 페이지를 한 단 두자고 제안하고 구현", problem: "추가검사 키트에 인쇄되는 QR이 목적지 URL을 직접 가리키면 URL이 바뀔 때 이미 배포된 키트를 되돌릴 수 없음", solution: "팀이 제어하는 브릿지 웹 페이지를 한 단 두고 거기서 포워딩하자고 제안하고 구현", result: "지금은 그 페이지가 Airbridge 링크로 넘겨 추가분석 약관 동의 페이지에 도착", lesson: "인쇄되어 나간 것은 되돌릴 수 없으니 팀이 제어하는 층을 한 단 둔다", contribution: "제안·구현", kinds: ["user-problem", "tech-review"] },
  { id: "crm-entry", layer: "user", node: "crm", tier: "brief", title: "상담 진입 경로가 앱 밖으로 넓어짐", when: "2023 ~ 2024", summary: "알림톡·앱 푸시·상담사용 웹뷰로 진입 경로가 넓어져 앱 밖 플랫폼마다 진입 페이지와 모니터링 범위를 구현", problem: "PM이 상담 진입 경로를 알림톡 유입 브릿지, 실손·건강검진 앱 푸시 캠페인 인앱 페이지, 상담사용 웹뷰로 넓히면서 CRM 영역까지 매출 구간이 됨", solution: "앱 밖 플랫폼마다 진입 페이지를 구현하고, 지켜야 할 모니터링 범위를 그만큼 넓힘" },
  { id: "sot-age-limit", layer: "team", node: "context", tier: "brief", title: "보험 · 보장분석", when: "2023", note: "보험진단", summary: "발병률 나이 제한을 프론트에서 재계산하지 않고 서버 에러 결과를 그대로 노출", solution: "발병률 나이 제한을 프론트에서 재계산하지 않고 서버 에러 결과를 그대로 노출", decision: "정책이 두 곳에 생기지 않게 하는 것을 우선" },
  { id: "sot-premium-logic", layer: "team", node: "context", tier: "brief", title: "보험 · 보험료 줄이기", when: "2026", note: "UX 개선", summary: "프론트에도 있던 실손보험료 로직을 서버가 새 필드로 내려주는 것으로 합의", problem: "실손보험료 비즈니스 로직이 프론트에도 있어 QA 대응마다 스펙 복잡성이 커짐", solution: "PM·서버 개발자에게 제기해 서버가 새 필드를 내려주는 것으로 합의", kinds: ["tech-review"] },
  { id: "techspec-in-repo", layer: "team", node: "context", tier: "brief", title: "프로젝트 맥락을 LLM이 닿는 곳으로: 테크스펙 레포 이관", when: "2026", summary: "구글 독스의 테크스펙을 코드 옆 마크다운으로 옮기고 표준 생성 스킬로 팀 공유", problem: "테크스펙이 구글 독스에 있어 LLM이 프로젝트 맥락을 읽을 수 없었음", solution: "코드 옆 마크다운으로 옮기고 표준 생성 스킬로 만들어 팀 공유", decision: "작업 전에 쓰는 문서라 그대로 계획서가 되어 LLM이 청크 단위로 작업하기 좋은 구조라고 판단" },
  { id: "adr-pipeline", layer: "team", node: "context", tier: "brief", title: "개발의 방향과 결정 맥락을 LLM이 닿는 곳으로: ADR·회의록 체계", when: "2026", summary: "구두로 흩어지던 회의 결정과 액션을 회의록·액션 티켓·ADR로 모으고 주간 ADR 자동 PR로 근거를 남김", problem: "회의 결정과 액션이 구두로 흩어짐", solution: "회의록·액션 티켓·ADR로 한 곳에 모으고, 회의록은 Jira 티켓으로 관리해 LLM이 접근할 수 있게 함. 주간 ADR 자동 PR로 결정이 나온 주에 근거까지 남김", decision: "개발의 방향성과 의사결정 맥락을 LLM이 알아야 더 많은 맥락 위에서 좋은 결정이 나온다고 봄" },
  { id: "agent-harness", layer: "team", node: "context", tier: "featured", title: "에이전트 하네스의 조직 레이어: 맥락·절차·게이트", when: "2026", summary: "Claude Code 위에 조직의 방식대로 일하게 하는 레이어를 AGENTS.md·스킬·게이트로 레포 안에 구축", problem: "LLM이 코드만 보고는 도메인 규칙과 외부 제약을 알 수 없고, 반복 작업마다 사람이 설명해야 했음", solution: "맥락은 AGENTS.md로, 페이지 스캐폴딩·스타일 토큰 lint·URL 검토·부채 평가·404 집계 같은 반복 작업은 스킬로, PR 전 셀프 리뷰와 윤문 훅은 게이트로 레포 안에 구축", result: "사람이 매번 설명하지 않아도 같은 결과가 나옴", contribution: "레이어 설계·구축 주도", kinds: ["team-efficiency", "tech-review"] },
  { id: "monorepo-migration", layer: "team", node: "gate", tier: "brief", title: "health-web을 모노레포로 이관", when: "2023.04", summary: "건강 앱을 enterprise-web 구조에 맞게 옮기고 copybara 동기화를 제거해 이관 완료", solution: "인프라 세팅은 플랫폼 쪽이 맡고, 건강 앱을 enterprise-web 구조에 맞게 옮김. 패키지 정렬, 타입 에러 정리, transpilePackages, 에셋 CDN lint, 배포 후 슬랙 알림, linkerd 경로 정리", result: "두 레포를 동기화하던 copybara를 제거해 이관을 마침", kinds: ["tech-review"] },
  { id: "deploy-guard", layer: "team", node: "gate", tier: "featured", title: "배포 절차를 모두가 실수 없이 따르게", when: "2026", summary: "배포 내역 대조를 자동화해 챕터 필수 프로세스로 만들고, 태그 race와 점유 배포 덮어쓰기를 코드로 차단", problem: "회사가 정한 모노레포 배포 절차가 사람마다 다르게 수행됨. build·publish 잡의 참조 시점 차이로 태그가 어긋나는 race", solution: "배포 내역을 손으로 대조하던 단계를 티켓 자동 추출 스크립트로 바꾸고 챕터 필수 프로세스로 만듦. 트리거 시점 SHA 고정으로 race 제거, 점유 배포가 타인 검수를 덮지 않도록 직전 싱크 SHA 기준 ancestor 검사", decision: "절차를 문서로 알리는 대신 코드가 막게 해야 누구나 같은 결과가 나온다고 판단. 모노레포 빌드·배포 구조를 이해해야 가능했던 개선", lesson: "절차는 문서로 알리는 것이 아니라 코드가 막게 해야 누구나 같은 결과가 나온다", contribution: "스크립트·가드 구현, 챕터 프로세스화 주도", kinds: ["team-efficiency", "tech-review"] },
  { id: "tracking-link-guard", layer: "team", node: "gate", tier: "featured", title: "트래킹 링크 사전 검증", when: "2026", summary: "오류 트래킹 링크로 유입 채널 unknown이 급증하자 24시간 안에 검증 스킬·프리뷰·가이드 4건을 만들어 배포 전에 걸리게 함", problem: "비개발자가 만드는 트래킹 링크가 QA 없이 배포돼 URL 오타로 유입 채널 unknown이 급증", solution: "5whys 후 24시간 안에 링크 검증 스킬·프리뷰·가이드 4건 제작", result: "오류 링크가 배포되기 전에 걸림", metric: "24시간", metricLabel: "5whys 뒤 도구 4건", contribution: "5whys 뒤 도구 4건 24시간 안에 단독 제작", kinds: ["team-efficiency"] },
  { id: "cms-strapi", layer: "team", node: "gate", tier: "brief", title: "콘텐츠를 CMS로", when: "2022 ~ 2024", summary: "캠페인 페이지를 Strapi에 붙여 마케터가 배포 없이 열게 하고, 정적 콘텐츠는 KVS로 이동", problem: "캠페인 페이지와 워딩 변경마다 개발 배포가 필요했음", solution: "카드 연동 시 유전자검사권을 주는 캠페인 이벤트 페이지를 사내 CMS(Strapi)에 붙여 정적 페이지로 제작. footer 같은 정적 콘텐츠는 KVS로 이동", result: "마케터가 개발 배포 없이 캠페인을 열고, 워딩 변경마다 배포하던 부담 제거", kinds: ["team-efficiency", "tech-review"] },
  { id: "ssr-guard", layer: "team", node: "gate", tier: "brief", title: "SSR 민감정보 가드", when: "2026", summary: "SSR prefetch 결과가 HTML에 노출된 문제에 dehydrate 직전 런타임 가드와 Sentry 감지를 두어 방어선 추가", problem: "SSR prefetch 결과가 HTML에 직렬화되어 노출", cause: "서버가 걸러서 내려보내야 할 데이터가 그대로 내려옴", solution: "서버가 놓쳐도 HTML에 실리지 않도록 dehydrate 직전 런타임 가드와 Sentry 감지를 프론트에 둠", decision: "근본 원인은 서버 쪽이지만 프론트에 방어선을 한 겹 더 두는 편이 안전하다고 판단", kinds: ["tech-review"] },
  { id: "spec-proposal-gate", layer: "team", node: "procedure", tier: "brief", title: "개발·기획 협업 체계", when: "2026", summary: "variation 판정 기준을 스펙 조정 제안 형식과 리뷰 게이트로 협약화하고 제안문 작성 스킬을 레포에 둠", problem: "개발자마다 달랐던 variation 판정 기준", solution: "스펙 조정 제안 형식·리뷰 게이트로 협약화하고, 제안문 작성 스킬을 레포에 둠", decision: "기준이 사람이 아니라 도구에 남아야 유지된다고 판단" },
  { id: "three-doc-principle", layer: "team", node: "procedure", tier: "brief", title: "팀마다 다르던 문서 정의를 원칙으로", when: "2026", summary: "tech-spec·README·AGENTS.md의 독자·시간축·질문을 나누고 한 줄 판별법과 갱신 원칙을 팀 합의", problem: "AGENTS.md가 등장하면서 tech-spec·README·AGENTS.md의 경계가 팀마다 달라짐", solution: "세 문서의 독자·시간축·답하는 질문을 나누고, 누수 방지 규칙과 기능 버전이 바뀔 때의 갱신 원칙을 문서로 만들어 팀 합의", decision: "“6개월 뒤에도 그대로여야 의미가 있는가”, “이게 없으면 AI가 잘못된 코드를 짤 위험이 있는가” 같은 한 줄 판별법으로 누구나 같은 판단을 하게 함", result: "챕터 표준으로 올릴 예정" },
  { id: "pre-review", layer: "team", node: "gate", tier: "featured", title: "PR 리뷰 레이어를 챕터 인프라로: pre-review", when: "2026", summary: "3시간 만에 시작한 셀프 리뷰 스킬을 챕터 룰셋 기반 리뷰 인프라로 키워 방향과 구축을 주도", problem: "리뷰어 부재일(solo-day), 1인 체제 팀, PM 같은 비개발 기여자의 PR, 금감원·망분리로 외부 리뷰 서비스를 쓸 수 없는 제약이 겹침", solution: "조직 규칙을 검증하고 내가 짠 코드가 전반적으로 괜찮은지 추론으로 확인하는 셀프 리뷰 스킬로 3시간 만에 시작. 리뷰 레이어를 인프라 단에 두고 챕터 단위 룰셋으로 정의", decision: "개인 도구로 두지 않고 변경 파일별로 리뷰 레이어를 라우팅하는 구조로 확장하는 방향으로 수렴, 방향과 구축을 주도", metric: "3시간", metricLabel: "셀프 리뷰 스킬로 시작", contribution: "방향과 구축 주도", kinds: ["team-efficiency", "tech-review"] },
  { id: "debt-okr", layer: "team", node: "procedure", tier: "brief", title: "기술부채를 OKR로", when: "2023 ~ 2026", summary: "분기마다 부채를 세 축으로 묶어 팀 OKR에 올리고, 평가 루브릭과 장부를 스킬로 만들어 기준이 도구에 남게 함", solution: "분기마다 팀원들과 부채를 뽑아 제품 개선·개발 환경·옵저버빌리티 세 축으로 묶고 담당자를 정해 팀 OKR에 올림. 2023년부터 운영", decision: "2026년에는 부채 평가 루브릭과 장부를 스킬로 만들어 산정 기준이 사람이 아니라 도구에 남게 함" },
  { id: "monthly-retro", layer: "team", node: "procedure", tier: "brief", title: "월간 회고", when: "2021 ~", note: "건강 웹팀", summary: "매달 Continue·Stop·Start를 쓰고 액션아이템을 뽑는 자리 운영", solution: "한 달을 돌아보며 각자 Continue·Stop·Start를 쓰고 액션아이템을 뽑는 자리를 매달 운영", result: "커뮤니티에 가까운 편한 자리라 평소 말하지 않던 문제가 잘 나옴" },
  { id: "solo-day", layer: "team", node: "procedure", tier: "featured", title: "병목과 회귀를 절차로", when: "2026", summary: "공통 영역 1인 병목을 도메인별 책임 그룹 9개와 solo-day 워크플로로 대체", problem: "공통 영역 1인 병목", solution: "도메인별 책임 그룹 9개와 2계층 원칙 문서, 리뷰어 부재일에도 머지되는 solo-day 워크플로, 공용 컴포넌트 수정 분리 원칙", decision: "파트마다 맥락을 가진 사람이 결정하도록 권한을 나누는 편이 병목을 없앤다고 판단", contribution: "책임 그룹·원칙 문서·워크플로 설계 주도", kinds: ["team-efficiency"] },
  { id: "book-club", layer: "team", node: "capability", tier: "brief", title: "팀 책모임·스터디 운영", when: "2022", summary: "책모임과 스터디 4개, 트렌드용 ZZAM 스터디를 열어 팀이 같은 기준으로 이야기하게 함", solution: "프로그래머의 뇌 읽기 모임, Josh Comeau CSS 스터디, Patterns.dev 디자인 패턴 스터디, 구글 엔지니어는 이렇게 일한다 책모임. 트렌드용 ZZAM 스터디는 각자 고른 개발 아티클을 30분 읽고 10분씩 리뷰", result: "팀이 같은 기준으로 코드와 일하는 방식을 이야기할 수 있게 됨" },
  { id: "pm-seo-10", layer: "team", node: "capability", tier: "featured", title: "일을 밀기 전에 역량부터 맞추기: PM SEO 10강", when: "2026", summary: "PM 요청으로 SEO 10강 커리큘럼을 설계해 여섯 번에 걸쳐 전부 진행, 들은 개발자가 스캐폴딩 스킬을 직접 만듦", problem: "검색 유입을 중요하게 보고 인덱싱 정리를 먼저 해 놓았지만 함께 밀 PM의 역량이 아직 맞지 않았음", solution: "정리 결과를 공유하자 PM이 싱크업을 요청. 수집, 이해와 판단, 신뢰와 선택, 랭킹 네 레이어로 10강 커리큘럼을 설계해 2026년 1월부터 4월까지 여섯 번에 걸쳐 전부 진행", decision: "일을 밀기 전에 기준부터 맞춰야 일이 간다고 판단", result: "강의를 들은 웹 개발자가 SEO 메타 스캐폴딩 스킬을 직접 만듦", lesson: "일을 밀기 전에 함께 밀 사람의 기준부터 맞춘다", contribution: "커리큘럼 설계와 강의 전부", kinds: ["team-efficiency"] },
  { id: "daangn-host", layer: "misc", node: "leave", tier: "brief", title: "당근 모임에서 육아 모임장 운영", summary: "사용자 쪽에서 모임 제품을 겪음" },
  { id: "leave-activities", layer: "misc", node: "leave", tier: "brief", title: "멘토링·발표·글", summary: "항해 플러스 프론트엔드 주니어 멘토링 (~2025.02), 서울시여성가족재단 Women Tech Week 발표 (2024.10), 블로그 4편" },
  { id: "goodoc-pseo", layer: "misc", node: "goodoc", tier: "featured", title: "시술백과 프로그래매틱 SEO", when: "2020.07 ~ 09", summary: "검색 키워드 분석으로 콘텐츠를 기획하고 수천 개 페이지를 정적 생성, 인덱싱 2천 건 증가·전환율 200% 상승", problem: "검색으로 들어오는 신규 유저를 늘릴 콘텐츠가 없었음", solution: "검색 로그와 내부 검색 키워드를 분석해 콘텐츠 유형을 추상화하고, 상담 상품 구매 데이터로 시술별 통계 페이지를 기획. 시술·상품 데이터를 템플릿에 넣어 수천 개 페이지를 Gatsby로 정적 생성", decision: "대량의 상품 데이터별 SEO 페이지가 필요해 정적 생성기 기반으로 설계 (기획·개발 main)", result: "인덱싱 2천 건 증가, 전환율 200% 상승", metric: "2천 건 · 200%", metricLabel: "인덱싱 증가 · 전환율 상승", contribution: "기획 main·개발 main, 분석은 sub", kinds: ["user-problem", "tech-review"] },
  { id: "goodoc-mask", layer: "misc", node: "goodoc", tier: "brief", title: "마스크 스캐너", when: "2020.02 ~ 03", summary: "공적 마스크 재고 API와 지도로 주변 약국 재고를 보여 주는 웹뷰 서비스 개발", problem: "코로나 초기 마스크 재고를 알 수 없어 약국을 돌아다녀야 했음", solution: "정부 공적 마스크 재고 API와 Naver Map API로 주변 약국 재고를 지도에서 보여 주는 서비스를 앱 안 웹뷰로 개발", result: "Plazma 발표 “굿닥 데이터로 극복하는 COVID-19” (2020.10)로 경험 공유" },
  { id: "goodoc-ugc", layer: "misc", node: "goodoc", tier: "brief", title: "후기 UGC", when: "2018.05 ~ 07", summary: "상담 상품에 사용자 콘텐츠가 없어 후기 기능을 설문형과 글형으로 개발", problem: "성형·시술 상담 상품에 사용자 콘텐츠가 없었음", solution: "자발적 커뮤니티 형성을 목표로 후기 등록·조회를 설문형과 글형으로 개발. 트래킹 이벤트, web to app 딥링크" },
  { id: "goodoc-talk", layer: "misc", node: "goodoc", tier: "brief", title: "굿닥톡 커뮤니티", when: "2020 ~ 2021", summary: "후기로 시작한 사용자 콘텐츠를 질문 게시판형 커뮤니티로 확장, 앱 안 웹뷰에 개발", solution: "질문 게시판형 커뮤니티. 카테고리 탭(인기·전체·건강·치과), 글쓰기, 댓글, 좋아요를 갖춘 화면을 React로 앱 안 웹뷰에 개발 (개발 main)" },
  { id: "goodoc-admin", layer: "misc", node: "goodoc", tier: "brief", title: "병원 관계자 어드민 v2", when: "2018 ~ 2019", summary: "광고 상품 계약·충전금·신청자 내역, 병원 접수 관리 어드민 초기 설계", solution: "광고 상품 계약·충전금·신청자 내역, 병원 접수 관리 어드민 초기 설계. 내부 운영 도구 다수" },
  { id: "talks", layer: "misc", node: "share", tier: "list", title: "발표", summary: "2019년부터 2024년까지 외부 발표 4회", items: ["개발자로 롱런하는 방법: 문제점을 발굴할 수 있는 개발자, 서울시여성가족재단 2024 Women Tech Week (2024.10)", "굿닥 데이터로 극복하는 COVID-19, Plazma (2020.10)", "아토믹 패턴으로 디자이너와 협업하기, Google DevFest Seoul (2019.10)", "기록하며 성장하기, Google Cloud Busan WTM (2019.07)"] },
  { id: "mentoring", layer: "misc", node: "share", tier: "list", title: "멘토링·강의", summary: "데브코스 멘토, 항해 플러스 멘토링, 실무 강의 제작, 영상강의", items: ["K-Digital Training 데브코스 멘토 (2022.02 ~)", "항해 플러스 주니어 멘토링 (2024.03 ~ 2025.02)", "스파르타 실무 강의 제작 (2024.07)", "프로그래머스 JS 영상강의 (2022.09)"] },
  { id: "writing", layer: "misc", node: "share", tier: "list", title: "글", summary: "기술 블로그 142편 (2017 ~), 글또 3년 (2018.02 ~ 2021.03)", items: ["디버깅에서 기본기로: [이미지 업로드 시 회전과 EXIF Orientation](https://feel5ny.github.io/2018/08/06/JS_13/) (2018), [unicode-range로 한글·영문 폰트 분리](https://feel5ny.github.io/2019/09/08/CSS_02/) (2019)", "앱 밖 유입의 출발점: [웹에서 앱으로 이동하기: 딥링크](https://feel5ny.github.io/2019/09/22/Communication_001/) (2019)", "제품 판단: [피츠의 법칙과 Touch Target](https://feel5ny.github.io/2021/01/24/ux-fitts-law/) (2021)", "3층의 근거: [좋은 결정은 맥락에서 나온다](https://feel5ny.github.io/2026/08/22/good-decisions-come-from-context/) (2026)"] },
  { id: "internal-lectures", layer: "misc", node: "share", tier: "list", title: "사내", summary: "PM 대상 SEO 10강, PM 챕터 AI 도구 특강과 전사 강의", items: ["PM 대상 SEO 10강 커리큘럼 설계·6회에 걸쳐 전 강 진행 (2026.01 ~ 04)", "PM 챕터 AI 도구 특강과 전사 강의 (2026)"] },
  { id: "gene-vendor-switch", layer: "product", node: "rollout", tier: "featured", title: "유전자 검사 업체 변경", when: "2022.09 ~ 12", note: "마크로젠 → 랩지노믹스", summary: "서비스를 멈추지 않고 검사 업체를 바꾸며 신청·동의·배송·반송·결과를 업체별로 분기하고 약관 12건을 반영", problem: "검사 업체가 바뀌는데 기존 신청자는 마크로젠 흐름을 끝까지 타야 하고, 신규 신청자는 새 업체의 약관·동의서·택배사·반송 안내를 봐야 함", solution: "서버가 내려주는 업체 enum을 진입 시 전역 상태에 두고 신청·동의·완료·배송·반송·결과 단계마다 필요한 곳에서만 분기. UI는 업체별 컴포넌트 두 벌, 데이터와 약관은 업체별 map 파일, 택배사는 업체별 매핑 검증", decision: "UI를 두 벌로 나눈 것은 마크로젠 흐름이 끝난 뒤 통째로 지우기 위해서. 데이터는 파라미터 분기로 두어 중복을 줄임", result: "무중단으로 업체 교체. 마크로젠 대규모 커뮤니케이션 대응 뒤 isMacrogen 고정과 클린업으로 마감. 약관·개인정보처리방침 12건 반영", lesson: "이행 기간이 있는 교체는 지울 수 있는 형태로 분기해야 클린업이 한 번에 끝난다", contribution: "웹 프론트엔드 분기 설계·구현과 약관 반영 담당(PR 기준 main)", kinds: ["tech-review", "user-problem"] },
  { id: "ssr-infra-misread", layer: "user", node: "infra", tier: "featured", title: "선착순 10시 502와 SSR 제거", when: "2022.05 ~ 08", note: "우회였던 해결", summary: "원인을 몰라 SSR을 걷어내 증상을 없앤 뒤, 3년에 걸쳐 같은 자리를 이해하고 방어선까지 만든 이야기", problem: "매일 오전 10시 선착순 오픈에 트래픽이 몰리면 SSR 서버가 502를 내 유저가 신청 화면에 못 들어감", cause: "SSR 서버 안에서 internal 대신 external 엔드포인트를 호출해 내부 요청이 외부 게이트웨이를 한 번 더 거치는 구조. 당시에는 인프라 구조를 몰라 원인을 찾지 못함", solution: "5XX 로그로 가장 많이 실패하는 마감 페이지부터 CSR로 바꿔 효과를 확인하고 신청·결과·반송·타임라인·외부 브릿지까지 SSR 제거. 증상은 사라짐", decision: "원인을 모른 채 렌더 위치를 옮긴 우회였다. 앱 안 레이어를 알아야 어느 층에서 문제가 나는지 짚을 수 있다는 것을 이때 배움", result: "2023년 모노레포 이관에서 k8s·linkerd·ingress를 직접 다루며 호출 경로를 이해. 2026년 SSR internal 호출 노출 문제에서는 원인(서버 데이터)과 방어선(dehydrate 직전 가드)을 나눠 대응", lesson: "증상이 사라진 것과 원인을 안 것은 다르다. 원인을 모르면 기록에 우회라고 적어 둔다", contribution: "당시 담당 개발자(단독). 2026년 가드는 설계·구현 주도", kinds: ["tech-review"] },
  { id: "insurance-mvp", layer: "product", node: "revenue-path", tier: "featured", title: "건강 보험 중개 MVP", when: "2023.08 ~ 09", summary: "보장분석·상세·보험 연동·선택 뷰·상담 신청·해피톡·상담사용 웹뷰까지 두 달 만에 출시", problem: "보험 중개라는 새 매출 구간을 두 달 안에 열어야 했고, 화면이 분석·상세·연동·선택·상담·상담사용 웹뷰로 넓었음", solution: "8월에 API·hook·mock을 먼저 만들고 페이지 흐름을 잡은 뒤 섹션 단위로 UI를 붙임. 해피톡 연동과 상담사용 웹뷰를 9월에 얹고 MVP 클린업으로 마감. 약관 3건 반영", result: "9월 말 MVP 출시. 10월부터 엠티뷰·모달·글자색 실험으로 이어짐. 이후 보험 2탭·상령일·CDP·보험 진단 웹으로 확장", contribution: "프론트엔드 웹 전체(PR 약 60건). 서버·PM·디자이너와 협업", kinds: ["user-problem"] },
];
