// src/app/sitemap.xml/route.ts
// 사이트맵 인덱스 (Hexo 구조와 동일)
export const dynamic = 'force-static';

const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://feel5ny.github.io';

export async function GET() {
  const now = new Date().toISOString();

  const sitemapIndex = `<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="sitemap.xsl"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <sitemap>
        <loc>${baseUrl}/post-sitemap.xml</loc>
        <lastmod>${now}</lastmod>
    </sitemap>
    <sitemap>
        <loc>${baseUrl}/category-sitemap.xml</loc>
        <lastmod>${now}</lastmod>
    </sitemap>
    <sitemap>
        <loc>${baseUrl}/tag-sitemap.xml</loc>
        <lastmod>${now}</lastmod>
    </sitemap>
</sitemapindex>
<!-- XML Sitemap generated by Nextra Blog Starter -->`;

  return new Response(sitemapIndex, {
    headers: {
      'Content-Type': 'application/xml',
    },
  });
}
